### PR TITLE
Added Dutch localisation and made a few grammar changes

### PR DESCRIPTION
**Pull request by J-o-s-e-p-h-L**
Simple changes to strings.

### CODE REVIEW

**Comment by tibbi** [comment]
Nice, thanks. Ive made the release notes untranslatable intentionally, as they are shown always just once after upgrading the app and so the translations are obviously always late. A couple extra strings might scare some translators so they just shouldnt be translated :)

**Comment by J-o-s-e-p-h-L** [comment]
No problem, I noticed strings to do with updates and the About page were missing, so I tried to find what I could.

**Comment by tibbi** [comment]
yea, there is a link at the bottom of the strings.xml, but I see that its pointing on the wrong website :) The correct one is https://github.com/SimpleMobileTools/Simple-Commons/tree/master/commons/src/main/res . Theres many more strings which are reused by multiple apps, so its enough to translate them once.

**Comment by J-o-s-e-p-h-L** [comment]
Thanks, I will do more translations and actual coding soon

**Pull request merged**
