### PR TITLE
implement shadow drawables programmatically

### PR DESCRIPTION
**Pull request by KryptKode**
# Notes
- add ShadowDrawable
- replace top icons to use ShadowDrawable
- changed the primary icon to `Blue` to test that the tinting was not broken

Top options

Flash modes

Aspect ratio mode

### CODE REVIEW

**Comment by tibbi** [comment]
nice, but it is too agressive, try using some grey instead of the black, also use a smaller shadowDY

**Comment by KryptKode** [comment]
> nice, but it is too agressive, try using some grey instead of the black, also use a smaller shadowDY

I had used  The `md_grey_400_dark` color. I will try a lighter color

**Comment by KryptKode** [comment]
Is this better @tibbi 
Used `shadowDy=2` and `shadowColor=md_grey_200_dark`
Screenshot 2022-10-10 at 19 33 31

**Comment by tibbi** [comment]
let me play around with it, I can do it already :)

**Pull request merged**
