### PR TITLE
Feature / migrating to target sdk 34

### PR DESCRIPTION
**Pull request by fatihergin**
- handle new READ_MEDIA_VISUAL_USER_SELECTED permission.
- now the app no longer forces media permission to run

### CODE REVIEW

**Comment by fatihergin** [comment]
waiting for https://github.com/SimpleMobileTools/Simple-Commons/pull/1781

**Comment by tibbi** [comment]
lets use the calculators binding for consistency please, it says
`private val binding by lazy(LazyThreadSafetyMode.NONE) { ActivityMainBinding.inflate(layoutInflater) }`

**Comment by fatihergin** [comment]
> lets use the calculators binding for consistency please, it says `private val binding by lazy(LazyThreadSafetyMode.NONE) { ActivityMainBinding.inflate(layoutInflater) }`

done

**Comment by tibbi** [comment]
thanks, should be good

**Pull request merged**
