### PR TITLE
Feature/adding location data to medias

### PR DESCRIPTION
**Pull request by fatihergin**

### CODE REVIEW

**Comment by tibbi** [comment]
nice, thanks

**Comment by tibbi** [comment]
improved the string a bit and moved it into commons

**Review by leuasseurfarrelds247-arch — COMMENTED** [review]
b48b01f969ab79be95a1ac6cda0d1c16a920bdce

**Comment by leuasseurfarrelds247-arch** [comment]
e957ce607a45457b6435527168b900d9f1e9b97a

**Comment by JimmysMaths** [comment]
@leuasseurfarrelds247-arch SimpleMobileTools apps were sold to ad and spyware company. 

Fork is here:
https://github.com/FossifyOrg

Discussion Here:
https://github.com/SimpleMobileTools/General-Discussion/issues/241

**Pull request merged**
