### PR TITLE
Create values-uk/strings.xml

### PR DESCRIPTION
**Pull request by motomoto7**
Added Ukrainian translation

### CODE REVIEW

**Comment by motomoto7** [comment]
Something wrong with the app_name string. 
Line 3  <string name="app_name">Просто Камера</string>   is correct, but it says  'Просто Камер' in Google App Store. Not sure why.

**Comment by tibbi** [comment]
copypaste error, thanks

**Comment by motomoto7** [comment]
Actually it is fine now, but yesterday a last letter was missing in a name of the app
Screenshot_2019-05-24-11-30-32_was_missing_yesterday

**Comment by tibbi** [comment]
ye I know, that was the copypasting error. Im inserting the app name in a different place, it isnt taken directly from the file.

**Comment by motomoto7** [comment]
Oh ok. So its fixed now. There may be another copypaste error in Simple Calendar Pro long description. I will write in a proper section.

**Pull request merged**
