### PR TITLE
add camera timer

### PR DESCRIPTION
**Pull request by KryptKode**
# Notes
- Add support for Camera Timer - Modes (`OFF`, `3s`, `5s` and `10s`)
- If the sound is enabled, play [Focus Complete Sound](https://developer.android.com/reference/android/media/MediaActionSound#FOCUS_COMPLETE) on each tick of the timer. Do we want to change this?

https://user-images.githubusercontent.com/25648077/204021657-6c243440-4baa-4214-beba-5b5388ed6b94.mp4

### CODE REVIEW

**Comment by tibbi** [comment]
remove the back flash and front blinking, it isnt needed. Keep the numbers countdown. The "x" on the shutter should be at the proper position since the beginning, remove the rotating animation. That is used at FAB buttons.

**Comment by KryptKode** [comment]
What about the sound? @tibbi  shall we keep or remove it?

**Comment by tibbi** [comment]
lets add some more silent beep, not that high frequency. Something deeper.

**Comment by KryptKode** [comment]
Any idea where I can get such a sound resource?

**Comment by KryptKode** [comment]
Hi @tibbi . 
I addressed all the changes

- [ ] remove rotating close icon from shutter button
- [ ] remove toggling flashlight on each countdown tick

For sound, I would address this in another pull request. I found some free sound resources [here](https://mixkit.co/free-sound-effects/countdown/)

**Comment by tibbi** [comment]
maybe the beeps could speed up before the capture, like other apps do it. Just so the user knows it is coming. Also it is unrelated to this task, but I just noticed that portrait photos keep showing upside down in the latest gallery. It shows up well initially, then as the zoomable subsampling-scale-imageview shows up, it is upside down.

**Comment by tibbi** [comment]
and also make sure the top icons are evenly aligned, if Flash is not visible. I guess that other buttons are always visible

camera

**Comment by KryptKode** [comment]
Hi @tibbi 
I addressed the issue with the top  icons not evenly spaced. 
I would address all beep sound related changes in another pull request to reduce scope of changes, if you don't mind. 

About the issue with images in portrait mode being upside down, I am using 6.25.0 Pro of Gallery and it works fine. I would investigate with the latest gallery app and make the changes in a future pull request.

**Comment by tibbi** [comment]
guess Ill check the upside down bug myself too, if you cannot reproduce it. Anyway, that isnt related to this task.

**Comment by KryptKode** [comment]
Yes, I couldn't reproduce it now with the latest master. Maybe if you could tell me the steps and the settings you have on both the camera and gallery apps, it might help.

**Comment by tibbi** [comment]
I keep reinstalling the apps, so everything is the default. It will be some rotation value somewhere, will take a look at it.

**Comment by tibbi** [comment]
apparently it breaks only if "Flip front camera photos horizontally" is enabled

**Comment by tibbi** [comment]
changes from ORIENTATION_ROTATE_270 to ORIENTATION_TRANSVERSE

**Comment by tibbi** [comment]
it keeps rotating chaotically in other galleries too, there is likely something wrong with setting those exif values. Maybe simply rotating the image itself and using orientation_normal would be better

**Pull request merged**
