### PR TITLE
Fix #57

### LINKED ISSUE #57: Don't persist 'Always' flash
Occasionally I want to force the flash on. When I come back to take a picture a day later, I seldom want the flash on and my first action is always to turn it off. Can we not persist this setting? Details:

- When I turn the flash off (not auto), I would not appreciate it reverting to auto. 
- When I force the flash on, if I quickly exit and return to the app, I would not appreciate having to turn the flash on again.

Therefore, I suggest the implementation of: when the app is opened (ie, in onCreate), if the persisted value is `always on`, change it to automatic.

### PR DESCRIPTION
**Pull request by trubitsyn**

### CODE REVIEW

**Comment by tibbi** [comment]
nice thanks, just please add the new "turn_flash_off_at_startup" string to all language files, even if obviously wont be translated

**Comment by trubitsyn** [comment]
Done.

**Comment by trubitsyn** [comment]
Done

**Comment by tibbi** [comment]
alright it works thanks, just try using more descriptive commit messages in the future :)

**Comment by trubitsyn** [comment]
Ah, well, thought it would be enough to reference the issue. Thank you for reviewing PRs :)

**Pull request merged**
