### PR TITLE
Add lockscreen note

### PR DESCRIPTION
**Pull request by hamishmb**
Note that one may have to disable the built-in camera app to use Simple Camera from the lockscreen.

Partially fixes: https://github.com/SimpleMobileTools/Simple-Camera/issues/360, relates to https://github.com/SimpleMobileTools/Simple-Camera/issues/281.

### CODE REVIEW

**Comment by tibbi** [comment]
that should be added as a FAQ item in that case, not into readme

**Comment by hamishmb** [comment]
Okay, I'll do that instead.

**Comment by hamishmb** [comment]
Where is the FAQ? I can't find it.

**Comment by tibbi** [comment]
I mean the in-app faq strings faq_1_title and faq_1_text

**Comment by hamishmb** [comment]
Okay, I'll get that sorted. Do I need to do anything in particular for the translations?

**Comment by tibbi** [comment]
well, if you arent a developer, likely not. I just have to see how to phrase it.

**Comment by hamishmb** [comment]
I am a developer, just not for this project. But if you're happy to change it, that's fine by me.

**Comment by tibbi** [comment]
well, you can suggest some FAQ question and answer if you want

**Comment by hamishmb** [comment]
I have realised that the FAQ isn't particularly discoverable in-app at the moment. I wouldn't have found it if you hadn't told me there was one. Are you sure we don't also want this in the readme?

**Comment by tibbi** [comment]
nobody reads github readme... At clicking on Rate us or on our email in the app there is a popup mentioning the FAQ first before both contacting us and rating.

**Comment by hamishmb** [comment]
Alright then, that makes sense.

**Pull request closed without merging**
